<!-- using internal DTD -->
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE employee [
    <!ELEMENT employee (name,salary)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT salary (#PCDATA)>]>
<employee>
    <name>XYZ</name>
    <salary>50k</salary>
</employee>

<!-- using external DTD -->
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE employee SYSTEM "13_emp.dtd">
<employee>
    <name>XYZ</name>
    <salary>50k</salary>
</employee>

<!-- 13__emp.dtd -->
<!ELEMENT employee (name,salary)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
